parameters:
    form.type.sonatra.select2.class: Sonatra\Bundle\FormExtensionsBundle\Form\Type\Select2Type
    form.type.sonatra.currency.class: Sonatra\Bundle\FormExtensionsBundle\Form\Type\CurrencyType

    form.type_extension.sonatra.datetime_jquery.class: Sonatra\Bundle\FormExtensionsBundle\Form\Extension\DateTimeJqueryTypeExtension
    form.type_extension.sonatra.date_jquery.class: Sonatra\Bundle\FormExtensionsBundle\Form\Extension\DateJqueryTypeExtension
    form.type_extension.sonatra.time_jquery.class: Sonatra\Bundle\FormExtensionsBundle\Form\Extension\TimeJqueryTypeExtension

services:
    # Select2
    form.type.sonatra.select2:
        class: '%form.type.sonatra.select2.class%'
        arguments: ['@service_container']
        abstract: true

    # Type
    form.type.sonatra.currency:
        class: '%form.type.sonatra.currency.class%'
        tags: [ { name: form.type, alias: currency } ]

    # Extension
    form.type_extension.sonatra.datetime_jquery:
        class: '%form.type_extension.sonatra.datetime_jquery.class%'
        tags: [ { name: form.type_extension, alias: datetime } ]

    form.type_extension.sonatra.date_jquery:
        class: '%form.type_extension.sonatra.date_jquery.class%'
        tags: [ { name: form.type_extension, alias: date } ]

    form.type_extension.sonatra.time_jquery:
        class: '%form.type_extension.sonatra.time_jquery.class%'
        tags: [ { name: form.type_extension, alias: time } ]
