parameters:
    sonatra.formextensions.twig.extension.base.class: Sonatra\Bundle\FormExtensionsBundle\Twig\Extension\FormExtension

services:
    sonatra.formextensions.twig.extension:
        public: false
        class: '%sonatra.formextensions.twig.extension.base.class%'
        arguments: ['@twig.form.renderer']
        tags: [ { name: twig.extension } ]
